[build]
# Use the custom build script that handles compiling the MCP client,
# installing all dependencies and building the frontend.
  command = "./netlify-build.sh"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=./netlify/functions --include=dev"

# Install dependencies for the functions
[build.processing.functions]
  node_bundler = "esbuild"

# Redirect API calls to the functions
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add CORS headers for the functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Ensure the custom build script is executable before the build starts
[build.lifecycle]
  onPreBuild = "chmod +x netlify-build.sh"

# Post-processing for functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["mcp-client-typescript/**"]
  # Mark mcp-client-typescript as external so esbuild does NOT bundle it;
  # the compiled output is copied via included_files instead.
  external_node_modules = ["mcp-client-typescript", "@anthropic-ai/sdk", "@modelcontextprotocol/sdk"]
