[build]
# Use the custom build script that handles compiling the MCP client,
# installing all dependencies and building the frontend.
  command = "./netlify-build.sh"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix=./netlify/functions --include=dev"

# Secrets scanning configuration
[build.processing]
  skip_processing = false

# Configure secrets scanning to ignore false positives
[build.processing.secrets]
  enabled = true
  # Ignore environment variable names that are not actual secrets
  omit_keys = ["VITE_WEBHOOK_URL", "VITE_APP_NAME", "VITE_APP_VERSION"]
  # Ignore build output files that may contain environment variable references
  omit_paths = ["dist/assets/*.js", "dist/assets/*.css"]

# Install dependencies for the functions
[build.processing.functions]
  node_bundler = "esbuild"

# Note: No need to redirect .netlify/functions/* - they work automatically

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add CORS headers for the functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Ensure the custom build script is executable before the build starts
[build.lifecycle]
  onPreBuild = "chmod +x netlify-build.sh"

# Post-processing for functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Mark external dependencies that should not be bundled by esbuild
  external_node_modules = ["mcp-client-typescript", "@anthropic-ai/sdk", "@modelcontextprotocol/sdk"]

# Development-specific overrides
[context.development.environment]
  MCP_DEBUG = "true"
