[build]
# Use the standard npm build process with prebuild script
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix=./netlify/functions --include=dev"
  # Disable secrets scanning for VITE_ environment variables
  SECRETS_SCAN_OMIT_KEYS = "VITE_WEBHOOK_URL,VITE_APP_NAME,VITE_APP_VERSION,VITE_GEMINI_API_KEY,VITE_ELEVENLABS_API_KEY,VITE_NOTION_API_KEY,VITE_CLERK_PUBLISHABLE_KEY,VITE_*"
  SECRETS_SCAN_OMIT_PATHS = "dist/**,**/*.js,**/*.css,**/*.ts,**/*.tsx"

# Secrets scanning configuration
[build.processing]
  skip_processing = false

# Configure secrets scanning to ignore false positives
[build.processing.secrets]
  enabled = true
  # Ignore environment variable names that are not actual secrets
  omit_keys = [
    "VITE_WEBHOOK_URL", 
    "VITE_APP_NAME", 
    "VITE_APP_VERSION",
    "VITE_GEMINI_API_KEY",
    "VITE_ELEVENLABS_API_KEY", 
    "VITE_NOTION_API_KEY",
    "VITE_CLERK_PUBLISHABLE_KEY",
    "VITE_*"
  ]
  # Ignore build output files that may contain environment variable references
  omit_paths = [
    "dist/assets/*.js", 
    "dist/assets/*.css",
    "dist/**/*",
    "**/*.js",
    "**/*.css"
  ]

# Install dependencies for the functions
[build.processing.functions]
  node_bundler = "esbuild"

# Note: No need to redirect .netlify/functions/* - they work automatically

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add CORS headers for the functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Prebuild hook to ensure dependencies are installed and configure secrets scanning
[build.lifecycle]
  onPreBuild = "npm install && export SECRETS_SCAN_OMIT_KEYS='VITE_WEBHOOK_URL,VITE_APP_NAME,VITE_APP_VERSION,VITE_GEMINI_API_KEY,VITE_ELEVENLABS_API_KEY,VITE_NOTION_API_KEY,VITE_CLERK_PUBLISHABLE_KEY,VITE_*' && export SECRETS_SCAN_OMIT_PATHS='dist/**,**/*.js,**/*.css,**/*.ts,**/*.tsx'"

# Post-processing for functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Mark external dependencies that should not be bundled by esbuild
  external_node_modules = ["mcp-client-typescript", "@anthropic-ai/sdk", "@modelcontextprotocol/sdk"]

# Development-specific overrides
[context.development.environment]
  MCP_DEBUG = "true"
